---
- name: "Create zone: {{ zone.name }} "
  ansible.posix.firewalld:
    permanent: true
    zone: "{{ zone.name }}"
    state: present
  notify:
    - "net.lafayette.firewalld :: Reload"

- name: "Configure zone: {{ zone.name }}.target={{ zone.target }}"
  vars:
    target_str: "{{ 'default' if (zone.target is undefined) else (zone.target) }}"
  ansible.posix.firewalld:
    permanent: true
    zone: "{{ zone.name }}"
    state: enabled
    target: "{{ target_str }}"
  notify:
    - "net.lafayette.firewalld :: Reload"

- name: "Configure zone: {{ zone.name }}.forward={{ forward_bool }}"
  vars:
    forward_bool: "{{ true if (zone.forward is undefined) else (not not zone.forward) }}"
  ansible.posix.firewalld:
    permanent: true
    zone: "{{ zone.name }}"
    state: enabled
    forward: "{{ forward_bool }}"
  notify: 
    - "net.lafayette.firewalld :: Reload"

- name: "Configure zone: {{ zone.name }}.masquerade={{ masquerade_bool }}"
  vars:
    masquerade_bool: "{{ false if (zone.masquerade is undefined) else (not not zone.masquerade) }}"
  ansible.posix.firewalld:
    permanent: true
    zone: "{{ zone.name }}"
    state: enabled
    masquerade: "{{ masquerade_bool }}"
  notify:
    - "net.lafayette.firewalld :: Reload"

- name: Zone interfaces
  loop: "{{ [] if zone.interfaces is undefined else zone.interfaces }}"
  loop_control:
    loop_var: interface
  firewalld:
      permanent: true
      zone: "{{ zone.name }}"
      state: enabled
      interface: "{{ interface }}"
  notify:
    - "net.lafayette.firewalld :: Reload"

- name: "Zone services"
  loop: "{{ [] if zone.services is undefined else zone.services }}"
  loop_control:
    loop_var: service
  ansible.posix.firewalld:
    permanent: true
    zone: "{{ zone.name }}"
    state: enabled
    service: "{{ service }}"
  notify:
    - "net.lafayette.firewalld :: Reload"

- name: "Zone ports"
  loop: "{{ [] if zone.ports is undefined else zone.ports }}"
  loop_control:
    loop_var: port
  ansible.posix.firewalld:
    permanent: true
    zone: "{{ zone.name }}"
    state: enabled
    port: "{{ port }}"
  notify:
    - "net.lafayette.firewalld :: Reload"

