---

- name: Install libdnf5 (required for dnf tasks)
  ansible.builtin.command:
    cmd: dnf install -y python3-libdnf5

  register: result
  changed_when: |-
    'Nothing to do' not in result.stdout
