---

- name: Install libdnf (required for dnf tasks)
  when: "ansible_pkg_mgr == 'dnf' or ansible_pkg_mgr == 'yum'"
  ansible.builtin.command:
    cmd: dnf install -y python3-libdnf

  register: result
  changed_when: |-
    'Nothing to do' not in result.stdout
