---

- name: Set up system connections
  loop: "{{ networking_connections }}"
  ansible.builtin.include_role:
    name: net.lafayette.connection

  vars:
    connection_name: "{{ item.name }}"
    connection_interface: "{{ item.interface }}"
    connection_ip_manual: "{{ item.ip_manual }}"
    connection_ipv4: "{{ item.ipv4 }}"
    connection_ipv4_cidr: "{{ item.ipv4_cidr }}"
    connection_zone: "{{ item.zone }}"
