router:
  hosts:
    marquis:
      ansible_host: 192.168.1.119

      dnsmasq_dns_port: 5353
      dnsmasq_interfaces: [] # Use dynamic bind
      dnsmasq_except_interfaces:
        - enp0s7 # Do not bind to public internet
      # dnsmasq_resolv: false
      # dnsmasq_neg_cache: true
      # dnsmasq_log_queries: false

      dnsmasq_address_records:
        - addresses: [10.1.10.1, 10.2.10.1]
          domains: [marquis]
