---
mediaserver:
  hosts:
    monolith:
      # What is ansible actually connecting to?
      ansible_host: monolith

      storage_dir: "/mnt/monolith"
      storage_mount_src: "UUID=162b7cb7-d108-496c-8864-4092695ac8c2"
      storage_mount_fstype: "auto" # guess

      sftp_readonly_user: "monolith"
      sftp_readonly_password: "monolith"
      sftp_write_group: "monolith-sftp-write"

      # XXX: This is only necessary because VLC on Nvidia SHIELD sucks
      sshd_support_sshrsa: true

      samba_server_domain_name: MONOLITH
      samba_server_workgroup: WORKGROUP
      samba_server_share_name: monolith
      samba_server_storage: "{{ storage_dir }}"

      deluged_storage_mount_path: "{{ storage_dir }}"
