---

- name: Install wg-vlan
  ansible.builtin.command:
    cmd: go install github.com/fsufitch/wg-vlan@latest
    creates: "{{ wireguard_wg_vlan_bin }}"

- name: Install Wireguard
  ansible.builtin.package:
    name: wireguard-tools
    state: present

- name: Get my public IP
  community.general.ipify_facts:

- name: Install Wireguard configurations
  loop: "{{ wireguard_configs }}"
  loop_control:
    loop_var: wireguard_item
    label: "{{ wireguard_item.id }}"
  ansible.builtin.include_tasks:
    file: item.yaml
