---

- name: Install required tooling
  ansible.builtin.dnf:
    name: NetworkManager
    state: present

- name: Set up external connection ({{ connection_.id }})
  community.general.nmcli:
    state: present
    conn_name: subnet-{{ connection_.id }}
    ifname: "{{ connection_.interface }}"

    type: ethernet
    method4: manual
    ip4:
      - "{{ connection_.ipv4 }}/{{ connection_.cidr }}"

    autoconnect: true
    conn_reload: true

- name: Con up
  community.general.nmcli:
    conn_name: subnet-{{ connection_.id }}
    state: up
