---

- name: Install Podman
  ansible.builtin.dnf:
    state: present
    name: podman

- name: Remove any native dnsmasq
  ansible.builtin.dnf:
    state: absent
    name: dnsmasq

- name: Create DHCP configuration file
  ansible.builtin.template:
    dest: /opt/lafayette/dnsmasq/{{ dnsmasq_.id }}/dnsmasq.conf
    mode: "0644"
    owner: root
    group: root
    src: dnsmasq.conf.j2
  register: dhcp_config_result

- name: Create/update podman network
  containers.podman.podman_network:
    name: "dnsmasq-{{ dnsmasq_.id }}"
    state: present
    driver: macvlan
    opt:
      mode: bridge
      parent: "{{ dnsmasq_.interface }}"
    ipam_driver: host-local
    subnet: "{{ dnsmasq_.ipv4 }}/{{ dnsmasq_.cidr }}"
    gateway: "{{ dnsmasq_.ipv4 }}"
    recreate: true
    force: true

- name: Create/update dnsmasq container
  containers.podman.podman_container:
    name: "dnsmasq-{{ dnsmasq_.id }}"
    image: docker.io/strm/dnsmasq
    state: present
    recreate: true
    network:
      - dnsmasq-{{ dnsmasq_.id }}
    # ip: "{{ dnsmasq_.ipv4 }}"
    # network: host
    # publish: []
    # expose: []
    # ports:
    #   - "{{ dnsmasq_.ipv4 }}:53:53/udp"
    #   - "{{ dnsmasq_.ipv4 }}:53:53/tcp"
    #   - "{{ dnsmasq_.ipv4 }}:67:67/udp"
    #   - "{{ dnsmasq_.ipv4 }}:68:68/udp"
    #   - "{{ dnsmasq_.broadcast }}:67:67/udp"
    #   - "{{ dnsmasq_.broadcast }}:68:68/udp"
    cap_add:
      - NET_ADMIN
      - NET_BIND_SERVICE
      - NET_BROADCAST
      - NET_RAW
    volumes:
      - /opt/lafayette/dnsmasq/{{ dnsmasq_.id }}/dnsmasq.conf:/etc/dnsmasq.conf
      - dnsmasq-var-{{ dnsmasq_.id }}:/var/lib/dnsmasq
  register: dnsmasq_container_result

- name: Create/update dnsmasq Systemd service
  containers.podman.podman_generate_systemd:
    name: "dnsmasq-{{ dnsmasq_.id }}"
    container_prefix: "podman"
    # Service is effectively: podman-dnsmasq-{{ dnsmasq_.id }}.service
    no_header: true
    force: true
    restart_policy: on-failure
    restart_sec: 10
    dest: /opt/lafayette/dnsmasq/{{ dnsmasq_.id }}/

  register: dnsmasq_service_result

- name: Link Systemd service
  ansible.builtin.file:
    path: /etc/systemd/system/podman-dnsmasq-{{ dnsmasq_.id }}.service
    state: link
    src: /opt/lafayette/dnsmasq/{{ dnsmasq_.id }}/podman-dnsmasq-{{ dnsmasq_.id }}.service

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart dnsmasq
  when: dhcp_config_result.changed or dnsmasq_container_result.changed or dnsmasq_service_result.changed
  ansible.builtin.systemd:
    name: podman-dnsmasq-{{ dnsmasq_.id }}.service
    state: restarted
