---

- name: Create dnsmasq service directory
  ansible.builtin.file:
    path: "{{ dnsmasq_dir }}"
    state: directory
    owner: root
    group: root
    mode: ug+rwx,o+rx

- name: Create dnsmasq config dropins directory
  ansible.builtin.file:
    path: "{{ dnsmasq_dir }}/conf.d"
    state: directory
    owner: root
    group: root
    mode: ug+rwx,o+rx

- name: Create dnsmasq var directory
  ansible.builtin.file:
    path: "{{ dnsmasq_dir }}/var"
    state: directory
    owner: root
    group: root
    mode: ug+rwx,o+rx


- name: Build dnsmasq image
  when: dnsmasq_image_build
  containers.podman.podman_image:
    name: "{{ dnsmasq_image }}"
    state: build
    force: true
    build:
      container_file: "{{ lookup('ansible.builtin.file', 'files/Containerfile') }}"

  notify:
    - "net.lafayette.dnsmasq :: Service updated"

- name: Create dnsmasq container config
  containers.podman.podman_container:
    name: "{{ dnsmasq_container_name }}"
    image: "{{ dnsmasq_image }}"
    state: quadlet

    quadlet_options:
      - |-
        [Service]
        Restart=always

        [Install]
        WantedBy=default.target

    network: host
    hostname: "{{ ansible_hostname }}"

    init: true

    cap_add:
      - NET_ADMIN
      - NET_BIND_SERVICE
      - NET_BROADCAST
      - NET_RAW
    volumes:
      - "{{ dnsmasq_dir }}/conf.d:/etc/dnsmasq.conf.d:z"
      - "{{ dnsmasq_dir }}/var:/var/lib/dnsmasq:rw,z"

  notify:
    - "net.lafayette.dnsmasq :: Service updated"


- name: Configure dnsmasq DNS base
  ansible.builtin.template:
    dest: "{{ dnsmasq_dir }}/conf.d/00-dns.conf"
    mode: "0644"
    owner: root
    group: root
    src: 00-dns.conf.j2
  notify:
    - "net.lafayette.dnsmasq :: Service updated"

- name: Create subnet DHCP config files
  loop: "{{ dnsmasq_dhcp_subnets }}"
  loop_control:
    loop_var: dnsmasq_dhcp_subnet

  ansible.builtin.template:
    dest: "{{ dnsmasq_dir }}/conf.d/01-dhcp-{{ dnsmasq_dhcp_subnet.name }}.conf"
    mode: "0644"
    owner: root
    group: root
    src: 01-dhcp.conf.j2
  notify:
    - "net.lafayette.dnsmasq :: Service updated"
