FROM docker.io/ubuntu:24.10 AS base

RUN apt-get update && \
    apt-get install -y proftpd && \
    rm -rf /var/lib/apt/lists/*

# RUN apk add proftpd proftpd-utils 

# Alpine proftpd does not create this dir by default, for some reason
# RUN mkdir -p /run/proftpd


FROM base AS passwd
ENTRYPOINT [ "ftpasswd", "--passwd", "--file", "/mnt/config/passwd" ]

FROM base AS server
CMD [ "proftpd", "-n", "-c", "/mnt/config/proftpd.conf" ]
