---

- name: Check valid inputs
  ansible.builtin.assert:
    that:
      - mount_source is defined
      - mount_source != ""
      - mount_destination is defined
      - mount_destination != ""
      - mount_fstype is defined
      - mount_fstype != ""
    fail_msg: "Mount arguments are invalid. mount_source={{ mount_source }}, mount_destination={{ mount_destination }}, mount_fstype={{ mount_fstype }}"

- name: Create mount point
  ansible.posix.mount:
    state: present
    src: "{{ mount_source }}"
    path: "{{ mount_destination }}"
    fstype: "{{ mount_fstype }}"
    opts: "{{ mount_options }}"
    dump: 0
    passno: 0
