---

- name: Bootstrap subnet connection ({{ subnet_id }})
  ansible.builtin.import_role:
    name: connection
  vars:
    connection_:
      id: "{{ subnet_.id }}"
      name: subnet-{{ subnet_.id }}
      interface: "{{ subnet_.interface }}"
      ipv4: "{{ subnet_.ipv4 }}"
      cidr: "{{ subnet_.cidr }}"
      zone: "{{ subnet_.zone }}"

- name: Bootstrap subnet dnsmasq ({{ subnet_id }})
  ansible.builtin.import_role:
    name: dnsmasq
  vars:
    dnsmasq_:
      id: "{{ subnet_.id }}"
      domain: "{{ subnet_.domain }}"
      interface: "{{ subnet_.interface }}"
      ipv4: "{{ subnet_.ipv4 }}"
      cidr: "{{ subnet_.cidr }}"
      dhcp: "{{ subnet_.dhcp }}"
