FROM alpine:latest

RUN apk add dnsmasq

RUN echo "conf-dir=/etc/dnsmasq.conf.d,*.conf" > /etc/dnsmasq.conf

RUN mkdir -p /var/lib/dnsmasq

VOLUME [ "/var/lib/dnsmasq" ]

CMD [ "dnsmasq", "-k", "--conf-file=/etc/dnsmasq.conf" ]
