---

- name: Set up Lafayette-style router
  hosts: router
  become: true

  roles:
    - net.lafayette.firewalld
    - net.lafayette.networking
    - net.lafayette.dnsmasq
    - net.lafayette.pihole
    - net.lafayette.wireguard

- name: Set up Lafayette-style media server
  hosts: mediaserver
  become: true

  roles:
    - net.lafayette.networking
    - net.lafayette.ftp_server
