---

- name: Fail if the sftp prefix is missing
  ansible.builtin.fail:
    msg: "The sftp user should start with the prefix 'sftp-'."
  when: sftp_server_user_name | regex_search('^sftp-') is not defined

- name: Check if the sftp user exists
  ansible.builtin.command: id -u "{{ sftp_server_user_name }}"
  register: sftp_server_user_check
  ignore_errors: true
  changed_when: false

- name: Create the sftp user
  when: sftp_server_user_update or sftp_server_user_check.rc
  ansible.builtin.user:
    state: present
    name: "{{ sftp_server_user_name }}"
    group: "{{ sftp_server_user_group }}"
    comment: "sftp user"
    shell: /sbin/nologin
    system: true
    create_home: false
    home: "{{ sftp_server_storage }}"

- name: Set the password for the sftp user
  when: sftp_server_user_password is not none and sftp_server_user_password != ""
  ansible.builtin.user:
    name: "{{ sftp_server_user_name }}"
    password: "{{ sftp_server_user_password | password_hash('sha512') }}"
    update_password: always
