---

- name: Create ftp server service directory
  ansible.builtin.file:
    path: "{{ ftp_server_service_dir }}"
    state: directory
    owner: root
    group: root
    mode: "ug+rwx,o+rx"

- name: Create config directory
  ansible.builtin.file:
    path: "{{ ftp_server_service_dir }}/config"
    state: directory
    owner: root
    group: root
    mode: "ug+rwx,o+rx"

- name: Create proftpd config file
  notify:
    - "net.lafayette.ftp_server :: Service updated"
  ansible.builtin.template:
    dest: "{{ ftp_server_service_dir }}/config/proftpd.conf"
    mode: "ug+rw,o+r"
    owner: root
    group: root
    src: proftpd.conf.j2

- name: Touch proftpd passwd file
  ansible.builtin.file:
    dest: "{{ ftp_server_service_dir }}/config/passwd"
    state: touch
    owner: root
    group: root
    mode: "ug+rw"

- name: Check ftp storage
  ansible.builtin.stat:
    path: "{{ ftp_server_storage }}"
    follow: false  # if it's a symlink, that's fine
  register: ftp_server_storage_stat

- name: Initialize ftp storage
  when: ftp_server_storage_stat.stat.islnk is not defined
  notify:
    - "net.lafayette.ftp_server :: Service updated"
  block:
    - name: Create ftp storage as directory (no link defined)
      when: not ftp_server_storage_link_to
      ansible.builtin.file:
        path: "{{ ftp_server_storage }}"
        state: directory
        owner: root
        group: root
        mode: "ug+rwx,o+rx"

    - name: Create ftp storage as symlink
      when: ftp_server_storage_link_to
      ansible.builtin.file:
        path: "{{ ftp_server_storage }}"
        state: link
        force: true
        src: "{{ ftp_server_storage_link_to }}"


- name: Build ftp server image
  when: ftp_server_image_build
  containers.podman.podman_image:
    name: "{{ ftp_server_image }}"
    state: build
    force: true
    build:
      container_file: "{{ lookup('ansible.builtin.file', 'files/Containerfile') }}"
      target: server

- name: Build ftp passwd image
  when: ftp_server_image_build
  containers.podman.podman_image:
    name: "{{ ftp_server_image }}-passwd"
    state: build
    force: true
    build:
      container_file: "{{ lookup('ansible.builtin.file', 'files/Containerfile') }}"
      target: passwd

  notify:
    - "net.lafayette.ftp_server :: Service updated"

# - name: Discover PASV address
#   ansible.builtin.debug:
#     msg: |-
#       hello {{ query('community.general.dig', ansible_hostname) }}

- name: Create passwd administration script
  notify:
    - "net.lafayette.ftp_server :: Service updated"
  ansible.builtin.template:
    dest: "{{ ftp_server_service_dir }}/passwd.sh"
    mode: "ug+rwx,o+rx"
    owner: root
    group: root
    src: passwd.sh.j2

- name: Create ftp server container config
  notify:
    - "net.lafayette.ftp_server :: Service updated"
  containers.podman.podman_container:
    name: "{{ ftp_server_container_name }}"
    image: "{{ ftp_server_image }}"
    state: quadlet

    quadlet_options:
      - |-
        [Service]
        Restart=always

        [Install]
        WantedBy=default.target

    init: true
    tty: true

    hostname: "{{ ansible_hostname }}"
    network: bridge
    ports:
      - "21:21/tcp"
      - "{{ ftp_server_pasv_min_port }}-{{ ftp_server_pasv_max_port }}:{{ ftp_server_pasv_min_port }}-{{ ftp_server_pasv_max_port }}/tcp"

    userns: "keep-id"
    cap_add:
      - CAP_SYS_ADMIN

    volumes:
      - "{{ ftp_server_service_dir }}/config:/mnt/config:ro,z"
      - "{{ ftp_server_storage }}:/mnt/ftp:rw,z"
